name: "per-lib-checks"
on: [push, pull_request, workflow_dispatch]
concurrency:
  group: build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cmake-build:
    name: Library CMake Build
    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 1
      matrix:
        gpu_backend: ["cuda"]
      fail-fast: false
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Add helpers directory to path
        run: echo "${PWD}/.github/workflows/helpers" >> $GITHUB_PATH

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: '${{ secrets.GITHUB_TOKEN }}'

      - uses: cachix/cachix-action@v14
        with:
          name: ff
          skipPush: true
          # authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: setup nix develop shell
        uses: nicknovitski/nix-develop@v1.1.0
        with:
          arguments: "--accept-flake-config .#ci"

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      # - name: Install system dependencies
      #   run: FF_GPU_BACKEND=${{ matrix.gpu_backend }} .github/workflows/helpers/install_dependencies.sh

      # - name: Install conda and FlexFlow dependencies
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     activate-environment: flexflow
      #     environment-file: packaging/conda/environment.yml
      #     auto-activate-base: false

      - name: Run cmake
        run: |
          cmake_${{ matrix.gpu_backend }}.sh

      - name: Build utils
        run: |
          build_libs.sh utils

      - name: Build op-attrs
        run: |
          build_libs.sh op-attrs

      - name: Build pcg
        run: |
          build_libs.sh pcg

      - name: Build kernels
        run: |
          build_libs.sh kernels

      - name: Build substitutions
        run: |
          build_libs.sh substitutions

      - name: Build compiler
        run: |
          build_libs.sh compiler

      - name: Test utils
        run: |
          test_libs.sh utils

      - name: Test substitutions
        run: |
          test_libs.sh substitutions

      - name: Test compiler
        run: |
          test_libs.sh compiler
      - name: Run lcov
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file main_coverage.info
          lcov --list main_coverage.info 
      - name: Upload coverage to CodeCov
        run: |
          bash <(curl -s https://codecov.io/bash) -f main_coverage.info
      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./build/coverage.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true